/// Generated by AssetsRefGenerator on 2020/03/27
class Res {
//  static const String fontawesome_webfont = "assets/fonts/fontawesome_webfont.ttf";
  static const String iconBarLogoTy = "assets/images/icon_bar_logo_ty.png";
  static const String iconBarLogoEg = "assets/images/icon_bar_logo_eg.png";
//  static const String user_vip_0 = "assets/images/vip/user_vip_0.png";
//  static const String user_vip_1 = "assets/images/vip/user_vip_1.png";
//  static const String user_vip_2 = "assets/images/vip/user_vip_2.png";
//  static const String user_vip_3 = "assets/images/vip/user_vip_3.png";
//  static const String user_vip_4 = "assets/images/vip/user_vip_4.png";
//  static const String user_vip_5 = "assets/images/vip/user_vip_5.png";
//  static const String user_vip_6 = "assets/images/vip/user_vip_6.png";

  static const String homeMemberAreaIconDeposit =
      "/images/index/idxusico_dsp.png";
  static const String homeMemberAreaIconWithdraw =
      "/images/index/idxusico_cash.png";
  static const String homeMemberAreaIconTransfer =
      "/images/index/idxusico_tsf.png";
  static const String homeMemberAreaIconVip = "/images/index/idxusico_vip.png";
}
